// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webgis02.Data;

#nullable disable

namespace webgis02.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221219103812_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webgis02.Models.HaLongRoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("ClassFunc")
                        .HasColumnType("smallint");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("Kind")
                        .HasColumnType("smallint");

                    b.Property<short?>("Level")
                        .HasColumnType("smallint");

                    b.Property<short?>("MaxSpeed")
                        .HasColumnType("smallint");

                    b.Property<short?>("Minspeed")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("ProvinceID")
                        .HasColumnType("smallint");

                    b.Property<long?>("SegmentID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("HaLongRoads");
                });
#pragma warning restore 612, 618
        }
    }
}
